# Generated by Django 3.2.6 on 2023-09-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='price',
            field=models.CharField(default=100, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(default='PUBG MOBILE Global', max_length=50),
        ),
    ]
