# Generated by Django 3.2.6 on 2023-09-07 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_category'),
        ('pubg_accounts', '0002_auto_20230906_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='category_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.category'),
            preserve_default=False,
        ),
    ]
