# Generated by Django 3.2.6 on 2023-09-08 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_alter_category_rasm'),
        ('pubg_accounts', '0003_account_category_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubgAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='PUBG MOBILE Global', max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=55)),
                ('level', models.CharField(max_length=10)),
                ('rp', models.CharField(max_length=255)),
                ('clothes', models.CharField(max_length=255)),
                ('skins', models.CharField(max_length=255)),
                ('titles', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PubgAccountMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='pubg/')),
                ('account_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubg_accounts.pubgaccount')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountmedia',
            name='account_fk',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountMedia',
        ),
    ]
