# Generated by Django 3.2.6 on 2023-09-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubg_accounts', '0004_auto_20230908_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pubgaccount',
            name='confirmed',
        ),
    ]
