# Generated by Django 3.2.6 on 2023-09-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubg_accounts', '0005_remove_pubgaccount_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubgaccount',
            old_name='status',
            new_name='status_type',
        ),
    ]
