# Generated by Django 3.2.6 on 2023-09-21 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pubg_accounts', '0006_rename_status_pubgaccount_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubgaccount',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='PubgAccountOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_phone', models.CharField(max_length=9)),
                ('order_status', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('account_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubg_accounts.pubgaccount')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PubgAccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.PositiveIntegerField()),
                ('price_paid_to_us', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('account_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubg_accounts.pubgaccount')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
