# Generated by Django 3.2.6 on 2023-09-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
