# Generated by Django 3.2.6 on 2023-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='sanded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
