# Generated by Django 3.2.6 on 2023-09-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
