# Generated by Django 3.2.6 on 2023-09-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_category_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
